### PR TITLE
The Cheat

### PR DESCRIPTION
**Pull request by nil0bject**
I don't really expect you to use this, but I was wondering how easy it was to pwn the other players.
It would be interesting to see a bot being able to defend itself from this attack.

Also, I ran out of time, but it's trivial to take control of the other bots and use them to destroy each other.

### CODE REVIEW

**Comment by davekinkead** [comment]
Yeah, I think the only way around this would be to freeze objects and use immutable functions instead.

**Comment by davekinkead** [comment]
Or copy each method during initialize, and hook into Object#method_added() to install them

**Comment by ghiculescu** [comment]
I predict this one will win in a landslide.

**Comment by elliotthilaire** [comment]
This could be more fun if was renamed (as to not give away it's powers), acted like a normal bot until it had low health, and then used its emp when your opponents thought they were about to win.

**Comment by hackling** [comment]
Seems a lot like https://github.com/davekinkead/battlebots/pull/5 :P

**Comment by davekinkead** [comment]
it does...

**Pull request merged**
